package constants

const (
	DefaultAWSRegion          = "eu-central-1"
	DefaultAWSAccessKeyID     = "test"
	DefaultAWSSecretAccessKey = "test"
	DefaultLocalStackEndpoint = "http://localhost:4566"
	DefaultAIWorkerGRPCAddr   = "localhost:50051"
	DefaultS3Bucket           = "raw-tickets-bucket"
	DefaultDynamoTable        = "ticket-hashes"
	DynamoPKAttr              = "PK"
	DynamoSKAttr              = "SK"
	DynamoS3KeyAttr           = "S3Key"
	DynamoFileNameAttr        = "FileName"
	DynamoWidthAttr           = "Width"
	DynamoHeightAttr          = "Height"
	DynamoSizeBytesAttr       = "SizeBytes"
	DynamoSKMeta              = "META"
	PrefixFile                = "FILE#"
	PrefixChunk               = "CHUNK#"
	PrefixFull                = "FULL#"
	S3PayloadKeyPrefix        = "payloads/"
	S3MetadataKeyPrefix       = "metadata/"
	StreamChunkBytes          = 2 * 1024 * 1024
	ChunkFallbackBytes        = 64 * 1024
	ChunkerPolynomial         = 0x3DA3358B4DC173
	StatusInserted            = "inserted"
	StatusReplaced            = "replaced"
	StatusDuplicateRejected   = "duplicate_rejected"
	FlagImage                 = "image"
	FlagVerbose               = "verbose"
	EnvS3EndpointURL          = "S3_ENDPOINT_URL"
	EnvDynamoEndpointURL      = "DYNAMODB_ENDPOINT_URL"
	EnvAWSRegion              = "AWS_REGION"
	EnvAWSAccessKeyID         = "AWS_ACCESS_KEY_ID"
	EnvAWSSecretAccessKey     = "AWS_SECRET_ACCESS_KEY"
	EnvDedupBucket            = "DEDUP_BUCKET"
	EnvMetadataTable          = "METADATA_TABLE"
	EnvAIWorkerGRPCAddr       = "AI_WORKER_GRPC_ADDR"
)
