// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: dedup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimilarityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityRequest) Reset() {
	*x = SimilarityRequest{}
	mi := &file_dedup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityRequest) ProtoMessage() {}

func (x *SimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityRequest.ProtoReflect.Descriptor instead.
func (*SimilarityRequest) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{0}
}

func (x *SimilarityRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SimilarityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityResponse) Reset() {
	*x = SimilarityResponse{}
	mi := &file_dedup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityResponse) ProtoMessage() {}

func (x *SimilarityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityResponse.ProtoReflect.Descriptor instead.
func (*SimilarityResponse) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{1}
}

func (x *SimilarityResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_dedup_proto protoreflect.FileDescriptor

const file_dedup_proto_rawDesc = "" +
	"\n" +
	"\vdedup.proto\x12\x05dedup\"'\n" +
	"\x11SimilarityRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"*\n" +
	"\x12SimilarityResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score2[\n" +
	"\x11SimilarityService\x12F\n" +
	"\x0fCheckSimilarity\x12\x18.dedup.SimilarityRequest\x1a\x19.dedup.SimilarityResponseB%Z#s3-dedup-engine/services/gateway/pbb\x06proto3"

var (
	file_dedup_proto_rawDescOnce sync.Once
	file_dedup_proto_rawDescData []byte
)

func file_dedup_proto_rawDescGZIP() []byte {
	file_dedup_proto_rawDescOnce.Do(func() {
		file_dedup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dedup_proto_rawDesc), len(file_dedup_proto_rawDesc)))
	})
	return file_dedup_proto_rawDescData
}

var file_dedup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dedup_proto_goTypes = []any{
	(*SimilarityRequest)(nil),  // 0: dedup.SimilarityRequest
	(*SimilarityResponse)(nil), // 1: dedup.SimilarityResponse
}
var file_dedup_proto_depIdxs = []int32{
	0, // 0: dedup.SimilarityService.CheckSimilarity:input_type -> dedup.SimilarityRequest
	1, // 1: dedup.SimilarityService.CheckSimilarity:output_type -> dedup.SimilarityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dedup_proto_init() }
func file_dedup_proto_init() {
	if File_dedup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dedup_proto_rawDesc), len(file_dedup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dedup_proto_goTypes,
		DependencyIndexes: file_dedup_proto_depIdxs,
		MessageInfos:      file_dedup_proto_msgTypes,
	}.Build()
	File_dedup_proto = out.File
	file_dedup_proto_goTypes = nil
	file_dedup_proto_depIdxs = nil
}
