// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: dedup.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageDedupService_ProcessImageStream_FullMethodName = "/dedup.v1.ImageDedupService/ProcessImageStream"
)

// ImageDedupServiceClient is the client API for ImageDedupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageDedupServiceClient interface {
	ProcessImageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImageChunk, ProcessImageResponse], error)
}

type imageDedupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageDedupServiceClient(cc grpc.ClientConnInterface) ImageDedupServiceClient {
	return &imageDedupServiceClient{cc}
}

func (c *imageDedupServiceClient) ProcessImageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImageChunk, ProcessImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageDedupService_ServiceDesc.Streams[0], ImageDedupService_ProcessImageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageChunk, ProcessImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageDedupService_ProcessImageStreamClient = grpc.ClientStreamingClient[ImageChunk, ProcessImageResponse]

// ImageDedupServiceServer is the server API for ImageDedupService service.
// All implementations must embed UnimplementedImageDedupServiceServer
// for forward compatibility.
type ImageDedupServiceServer interface {
	ProcessImageStream(grpc.ClientStreamingServer[ImageChunk, ProcessImageResponse]) error
	mustEmbedUnimplementedImageDedupServiceServer()
}

// UnimplementedImageDedupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageDedupServiceServer struct{}

func (UnimplementedImageDedupServiceServer) ProcessImageStream(grpc.ClientStreamingServer[ImageChunk, ProcessImageResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessImageStream not implemented")
}
func (UnimplementedImageDedupServiceServer) mustEmbedUnimplementedImageDedupServiceServer() {}
func (UnimplementedImageDedupServiceServer) testEmbeddedByValue()                           {}

// UnsafeImageDedupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageDedupServiceServer will
// result in compilation errors.
type UnsafeImageDedupServiceServer interface {
	mustEmbedUnimplementedImageDedupServiceServer()
}

func RegisterImageDedupServiceServer(s grpc.ServiceRegistrar, srv ImageDedupServiceServer) {
	// If the following call panics, it indicates UnimplementedImageDedupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageDedupService_ServiceDesc, srv)
}

func _ImageDedupService_ProcessImageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageDedupServiceServer).ProcessImageStream(&grpc.GenericServerStream[ImageChunk, ProcessImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageDedupService_ProcessImageStreamServer = grpc.ClientStreamingServer[ImageChunk, ProcessImageResponse]

// ImageDedupService_ServiceDesc is the grpc.ServiceDesc for ImageDedupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageDedupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dedup.v1.ImageDedupService",
	HandlerType: (*ImageDedupServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessImageStream",
			Handler:       _ImageDedupService_ProcessImageStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dedup.proto",
}
